# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('role', models.IntegerField(verbose_name=1)),
                ('phone', models.IntegerField(verbose_name=11)),
            ],
        ),
    ]
